import type { Metadata } from "next";
import { Poppins, DM_Sans } from "next/font/google";
import "./globals.css";
import { ModalProvider } from './context/ModalContext';
import { ToastProvider } from "./components/hooks/use-toast";
import { Toaster } from "@/app/components/ui/toaster";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${dmSans.variable} antialiased font-sans`}>
        <ModalProvider>
          <ToastProvider>
            {children}
            <Toaster />
          </ToastProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
